apiVersion: v1
data:
  prometheus.yml: |-
    global:
      scrape_interval:     15s
      evaluation_interval: 15s

    rule_files:
      - /etc/prometheus/rules/*.yaml


    scrape_configs:
            #      - job_name: prometheus
            #        static_configs:
            #          - targets: ['localhost:9090']

      - job_name: go-pg-crud
        static_configs:
          - targets: ['go-pg-crud.go-pg-crud.svc:80']

    # Alerting specifies settings related to the Alertmanager
    alerting:
      alertmanagers:
        - static_configs:
          - targets:
            # Alertmanager's default port is 9093
            - alertmanager:9093

kind: ConfigMap
metadata:
  name: prometheus-config
  labels:
    training-monitoring: 'true'

