apiVersion: v1
data:
  grafana.ini: |-
    [auth.basic]
    enabled = false

    [auth.anonymous]
    enabled = true
    org_name = Main Org.
    org_role = Viewer

    [paths]
    data = /var/lib/grafana
    logs = /var/lib/grafana/logs
    plugins = /var/lib/grafana/plugins
    provisioning = /etc/grafana/provisioning

    [server]
    http_port = 3000

    #[security]
    #disable_initial_admin_creation = true
    #admin_user = admin
    #admin_password = admin
    #secret_key = privetmirkey
kind: ConfigMap
metadata:
  name: grafana-config
  labels:
    training-monitoring: 'true'

