apiVersion: v1
data:
  # id пользователя telegram, который будет администратором бота
  admin: NjY3MDAxMzk=
  # токен бота telegram
  token: MTQ5MjcxMzg2NDpBQUhpUU5pNUlLSFNMNVA4dFRYQWZpdW50M25GVXoydmYyTQ==
kind: Secret
metadata:
  name: alertmanager-bot
  labels:
    training-monitoring: 'true'
type: Opaque
