apiVersion: v1
kind: Service
metadata:
  labels:
    training-monitoring: "true"
  name: alertmanager-bot
spec:
  clusterIP: 172.30.3.92
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: alermanager-bot
  sessionAffinity: None
  type: ClusterIP
